W8D1/reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :subs, except: [:destroy]
  resources :posts, except: [:index, :destroy]
end

W8D1/reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  content    :string
#  subject    :string           not null
#  url        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  author_id  :integer          not null
#  sub_id     :integer          not null
#
# Indexes
#
#  index_posts_on_author_id  (author_id)
#  index_posts_on_sub_id     (sub_id)
#

class Post < ApplicationRecord
    validates :subject, :author_id, :sub_id, presence: true

    belongs_to :author,
        primary_key: :id,
        foreign_key: :author_id,
        class_name: :User

    belongs_to :sub,
        primary_key: :id,
        foreign_key: :sub_id,
        class_name: :Sub
            
end

W8D1/reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :bigint           not null, primary key
#  description :string           not null
#  title       :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer          not null
#
# Indexes
#
#  index_subs_on_title    (title) UNIQUE
#  index_subs_on_user_id  (user_id)
#

class Sub < ApplicationRecord
    validates :title, :description, :user_id, presence: true
    validates :title, uniqueness: true

    belongs_to :moderator,
        primary_key: :id,
        foreign_key: :user_id,
        class_name: :User,
        inverse_of: :subs

    has_many :posts,
        primary_key: :id,
        foreign_key: :sub_id,
        class_name: :Post,
        inverse_of: :sub
    
end

W8D1/reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  password_digest :string           not null
#  session_token   :string           not null
#  username        :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_session_token  (session_token) UNIQUE
#  index_users_on_username       (username) UNIQUE
#

class User < ApplicationRecord
### ASPIRE
    validates :username, :session_token, :password_digest, presence: true
    validates :username, :session_token, uniqueness: true
    validates :password, length: { minimum: 6, allow_nil: true }
    before_validation :ensure_session_token

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        return nil unless user
        user.is_password?(password) ? user : nil
    end

    attr_reader :password

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest) == password
    end

    def ensure_session_token
        self.session_token ||= SecureRandom.urlsafe_base64
    end

    def reset_session_token!
        self.session_token = SecureRandom.urlsafe_base64
        self.save!
        self.session_token
    end

    has_many :subs, inverse_of: :moderator

    has_many :posts, inverse_of: :author

end

W8D1/reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
### CRLLL
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_login
        redirect_to new_session_url unless logged_in?
    end

    def logged_in?
        !!current_user
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
        @current_user = user
    end

    def logout!
        current_user.reset_session_token!
        @current_user = nil
        session[:session_token] = nil
    end

end

W8D1/reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :require_login, except: [:show]

    def show
        @post = Post.find_by(id: params[:id])
        @sub = Sub.find_by(id: @post.sub_id)
        @author = User.find_by(id: @post.author_id)
        render :show
    end

    def new
        @post = Post.new
        render :new
    end

    def create
        @post = Post.new(post_params)
        @post.author_id = current_user.id
        if @post.save
            redirect_to post_url(@post)
        else
            flash.now[:errors] = @post.errors.full_messages
            render :new
        end
    end

    def edit
        @post = Post.find_by(id: params[:id])
        if current_user.id != @post.author_id
            redirect_to post_url(@post)
        else
            render :edit
        end
    end

    def update
        @post = Post.find_by(id: params[:id])
        if @post.author_id != current_user.id
            flash.now[:errors] = ['You cannot edit someone else''s post.']
            render :edit
        else
            if @post.update(post_params)
                redirect_to post_url(@post)
            else
                flash.now[:errors] = @post.errors.full_messages
                render :edit
            end
        end
    end

    private
    
    def post_params
        params.require(:post).permit(:subject, :content, :url, :sub_id)
        ###missing author_id
    end
end

W8D1/reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:username],params[:user][:password])
        if @user
            login!(@user)
            redirect_to subs_url
        else
            flash[:errors] = ['Invalid Credentials']
            redirect_to new_session_url
        end
    end

    def destroy
        logout!
        redirect_to subs_url
    end

end

W8D1/reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :require_login, except: [:index, :show]
    # before_action :require_moderator, only: [:edit, :update]

    def index
        @subs = Sub.all
        render :index
    end

    def show
        @sub = Sub.find_by(id: params[:id])
        @moderator = User.find_by(id: @sub.user_id)
        @posts = Post.where(sub_id: @sub.id)
        render :show
    end

    def new
        @sub = Sub.new
        render :new
    end

    def create
        @sub = Sub.new(sub_params)
        @sub.user_id = current_user.id
        if @sub.save
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :new
        end
    end

    def edit
        @sub = Sub.find_by(id: params[:id])
        if current_user.id != @sub.user_id
            redirect_to sub_url(@sub)
        else
            render :edit
        end
    end

    def update
        @sub = Sub.find_by(id: params[:id])
        if @sub.user_id != current_user.id
            flash.now[:errors] = ['Permission Denied']
            render :edit
        else
            if @sub.update(sub_params)
                redirect_to sub_url(@sub)
            else
                flash.now[:errors] = @sub.errors.full_messages
                render :edit
            end
        end
    end

    private

    # def require_moderator
    #     return if current_user.subs.find_by(id: params[:id])
    #     render json: 'Forbidden', status: :forbidden
    # end

    def sub_params
        params.require(:sub).permit(:title, :description)
    end
end

W8D1/reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        render :index
    end

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login!(@user)
            redirect_to subs_url
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

W8D1/reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
    def auth_token
        "<input type='hidden'
                name='authenticity_token'
                value='<%= form_authenticity_token %>' >".html_safe
    end
end

W8D1/reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

W8D1/reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

W8D1/reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <header class="header">
        <div class="logo">
          <a href="<%= subs_url %>">
            <%= image_tag "logo.jpg" %>
          </a>
        </div>
        <% if logged_in? %>
        <div class="welcome">
          <p>Welcome, <%= current_user.username %></p>
        </div>
        <div class="nav-buttons">
          <form action="<%= session_url %>" method="POST">
            <input type="hidden" name="_method" value="DELETE">
            <%= auth_token %>
            <input type="submit" value="Sign Out">
          </form>
        </div>

        <% else %>
        <div class="welcome"></div>

        <div class="nav-buttons">
          <form action="<%= new_user_url %>" method="GET">
            <%= auth_token %>
            <input type="submit" value="Create Account">
          </form>

          <form action="<%= new_session_url %>" method="GET">
            <%= auth_token %>
            <input type="submit" value="Sign In">
          </form>
        </div>
        
        <% end %>
      </header>
    </div>

    <div class="wrapper">
    <% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |error| %>      
        <li><%= error %></li>
        <% end %>
      </ul>
    <% end %>
    </div>

    <div class="wrapper content">
      <main>
      <%= yield %>
      </main>

      <aside>
        <a href="<%= new_sub_url %>">Create a new subreddit</a>
      </aside>
    </div>
  </body>
</html>

W8D1/reddit_clone/app/views/users/index.html.erb
<h1>Index Placeholder</h1>

W8D1/reddit_clone/app/views/users/new.html.erb
<h1>New User</h1>

<form action="<%= users_url %>" method="POST">

    <label>Username:
        <input type="text" name="user[username]" value="<%= @user.username %>">
    </label>
    
    <label>Password:
        <input type="password" name="user[password]" value="<%= @user.password %>">
    </label>

    <%= auth_token %>
    
    <input type="submit" value="Create User">

</form>